./aws-go-s3-folder/Kulado.yaml
./aws-js-containers/Kulado.yaml
./aws-js-s3-folder/Kulado.yaml
./aws-js-s3-folder-component/Kulado.yaml
./aws-js-sqs-slack/Kulado.yaml
[01;32m./aws-js-webserver/Kulado.yaml[00m
[01;32m./aws-js-webserver-component/Kulado.yaml[00m
./aws-py-s3-folder/Kulado.yaml
./aws-py-stepfunctions/Kulado.yaml
./aws-py-webserver/Kulado.yaml
./aws-ts-airflow/Kulado.yaml
./aws-ts-apigateway/Kulado.yaml
./aws-ts-apigateway-auth0/Kulado.yaml
./aws-ts-appsync/Kulado.yaml
./aws-ts-assume-role/assume-role/Kulado.yaml
./aws-ts-assume-role/create-role/Kulado.yaml
./aws-ts-containers/Kulado.yaml
./aws-ts-eks/Kulado.yaml
./aws-ts-eks-hello-world/Kulado.yaml
./aws-ts-eks-migrate-nodegroups/Kulado.yaml
./aws-ts-hello-fargate/Kulado.yaml
./aws-ts-kulado-webhooks/Kulado.yaml
./aws-ts-resources/Kulado.yaml
./aws-ts-ruby-on-rails/Kulado.yaml
./aws-ts-s3-lambda-copyzip/Kulado.yaml
./aws-ts-serverless-raw/Kulado.yaml
./aws-ts-slackbot/Kulado.yaml
./aws-ts-stackreference/company/Kulado.yaml
./aws-ts-stackreference/department/Kulado.yaml
./aws-ts-stackreference/team/Kulado.yaml
./aws-ts-static-website/Kulado.yaml
./aws-ts-stepfunctions/Kulado.yaml
[01;32m./aws-ts-thumbnailer/Kulado.yaml[00m
./aws-ts-twitter-athena/Kulado.yaml
./aws-ts-url-shortener-cache-http/Kulado.yaml
./aws-ts-voting-app/Kulado.yaml
[01;32m./azure-js-webserver/Kulado.yaml[00m
./azure-py-aks/Kulado.yaml
./azure-py-webserver/Kulado.yaml
./azure-ts-aks-helm/Kulado.yaml
./azure-ts-aks-mean/Kulado.yaml
./azure-ts-aks-multicluster/Kulado.yaml
./azure-ts-api-management/Kulado.yaml
./azure-ts-appservice/Kulado.yaml
./azure-ts-appservice-devops/infra/Kulado.yaml
./azure-ts-appservice-docker/Kulado.yaml
./azure-ts-arm-template/Kulado.yaml
./azure-ts-dynamicresource/Kulado.yaml
./azure-ts-functions/Kulado.yaml
./azure-ts-functions-raw/Kulado.yaml
./azure-ts-hdinsight-spark/Kulado.yaml
./azure-ts-msi-keyvault-rbac/Kulado.yaml
./azure-ts-serverless-url-shortener-global/Kulado.yaml
./azure-ts-static-website/Kulado.yaml
./azure-ts-stream-analytics/Kulado.yaml
[01;32m./azure-ts-webserver/Kulado.yaml[00m
[01;32m./azure-ts-webserver-component/Kulado.yaml[00m
./cloud-js-api/Kulado.yaml
./cloud-js-containers/Kulado.yaml
./cloud-js-httpserver/Kulado.yaml
[01;32m./cloud-js-thumbnailer/Kulado.yaml[00m
[01;32m./cloud-js-thumbnailer-machine-learning/Kulado.yaml[00m
./cloud-js-twitter-athena/Kulado.yaml
./cloud-ts-url-shortener/Kulado.yaml
./cloud-ts-url-shortener-cache/Kulado.yaml
./cloud-ts-url-shortener-cache-http/Kulado.yaml
./cloud-ts-voting-app/Kulado.yaml
./digitalocean-ts-loadbalanced-droplets/Kulado.yaml
./f5bigip-ts-ltm-pool/f5bigip-ec2-instance/Kulado.yaml
./f5bigip-ts-ltm-pool/f5bigip-pool/Kulado.yaml
./f5bigip-ts-ltm-pool/nginx-ec2-instance/Kulado.yaml
./gcp-js-webserver/Kulado.yaml
./gcp-py-functions/Kulado.yaml
./gcp-py-gke/Kulado.yaml
./gcp-py-instance-nginx/Kulado.yaml
./gcp-ts-functions/Kulado.yaml
./gcp-ts-gke/Kulado.yaml
./gcp-ts-gke-hello-world/Kulado.yaml
./gcp-ts-k8s-ruby-on-rails-postgresql/infra/Kulado.yaml
./gcp-ts-serverless-raw/Kulado.yaml
./gcp-ts-slackbot/Kulado.yaml
./kubernetes-ts-configmap-rollout/Kulado.yaml
./kubernetes-ts-exposed-deployment/Kulado.yaml
./kubernetes-ts-guestbook/components/Kulado.yaml
./kubernetes-ts-guestbook/simple/Kulado.yaml
./kubernetes-ts-helm-wordpress/Kulado.yaml
./kubernetes-ts-jenkins/Kulado.yaml
./kubernetes-ts-nginx/Kulado.yaml
./kubernetes-ts-s3-rollout/Kulado.yaml
./kubernetes-ts-sock-shop/Kulado.yaml
./kubernetes-ts-staged-rollout-with-prometheus/Kulado.yaml
./linode-js-webserver/Kulado.yaml
./multicloud-ts-buckets/Kulado.yaml
./twilio-ts-component/Kulado.yaml
